//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public Administrator()
        {
            this.EventSpace = new HashSet<EventSpace>();
            this.FoodSupplier = new HashSet<FoodSupplier>();
            this.Equipment = new HashSet<Equipment>();
            this.Worker = new HashSet<Worker>();
            this.Message = new HashSet<Message>();
        }
    
        public string Phone_number { get; set; }
        public string Username { get; set; }
    
        public virtual ICollection<EventSpace> EventSpace { get; set; }
        public virtual ICollection<FoodSupplier> FoodSupplier { get; set; }
        public virtual ICollection<Equipment> Equipment { get; set; }
        public virtual ICollection<Worker> Worker { get; set; }
        public virtual ICollection<Message> Message { get; set; }
        public virtual RegisteredUser RegisteredUser { get; set; }
    }
}
