//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.EventSpaceReview = new HashSet<EventSpaceReview>();
            this.UserReview = new HashSet<UserReview>();
            this.Message = new HashSet<Message>();
            this.Reservation = new HashSet<Reservation>();
        }
    
        public bool Is_Blocked { get; set; }
        public int Rating { get; set; }
        public string Username { get; set; }
    
        public virtual ICollection<EventSpaceReview> EventSpaceReview { get; set; }
        public virtual ICollection<UserReview> UserReview { get; set; }
        public virtual ICollection<Message> Message { get; set; }
        public virtual ICollection<Reservation> Reservation { get; set; }
        public virtual RegisteredUser RegisteredUser { get; set; }
    }
}
