//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Administrator> Administrator { get; set; }
        public DbSet<Customer> Customer { get; set; }
        public DbSet<Discount> Discount { get; set; }
        public DbSet<Equipment> Equipment { get; set; }
        public DbSet<EquipmentCategory> EquipmentCategory { get; set; }
        public DbSet<EventSpace> EventSpace { get; set; }
        public DbSet<EventSpaceReview> EventSpaceReview { get; set; }
        public DbSet<FoodOrder> FoodOrder { get; set; }
        public DbSet<FoodSupplier> FoodSupplier { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<RegisteredUser> RegisteredUser { get; set; }
        public DbSet<Reservation> Reservation { get; set; }
        public DbSet<UserOrder> UserOrder { get; set; }
        public DbSet<UserReview> UserReview { get; set; }
        public DbSet<Worker> Worker { get; set; }
    }
}
