//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public Discount()
        {
            this.EventSpace = new HashSet<EventSpace>();
        }
    
        public double Discount_amount { get; set; }
        public System.DateTime Start_date { get; set; }
        public System.DateTime End_date { get; set; }
        public int Discount_id { get; set; }
        public string Creator { get; set; }
    
        public virtual Worker Worker { get; set; }
        public virtual ICollection<EventSpace> EventSpace { get; set; }
    }
}
