//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentOrder
    {
        public int Id { get; set; }
        public int Equipment { get; set; }
        public int UserOrder { get; set; }

        public EquipmentOrder()
        {
        }
        public EquipmentOrder(int eq, int ur)
        {
            this.Equipment = eq;
            this.UserOrder = ur;
        }
    
        public virtual Equipment Equipment1 { get; set; }
        public virtual UserOrder UserOrder1 { get; set; }
    }
}
