//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventSpace
    {
        public EventSpace()
        {
            this.EventSpaceReview = new HashSet<EventSpaceReview>();
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int EventSpace_id { get; set; }
        public string Address { get; set; }
        public double Size { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string Administator { get; set; }
        public int DiscountId { get; set; }
        public string Worker { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual Discount Discount { get; set; }
        public virtual ICollection<EventSpaceReview> EventSpaceReview { get; set; }
        public virtual ICollection<Reservation> Reservation { get; set; }
        public virtual Worker Worker1 { get; set; }
    }
}
