//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventSpaceReview
    {
        public int Code { get; set; }
        public string Text { get; set; }
        public int Rating { get; set; }
        public System.DateTime Date { get; set; }
        public int ReceivedSpace { get; set; }
        public string Creator { get; set; }

        public EventSpaceReview() { }
        public EventSpaceReview(int id, string logedInUser)
        {
            this.ReceivedSpace = id;
            this.Creator = logedInUser;
            this.Date = DateTime.Now;
        }

        public virtual Customer Customer { get; set; }
        public virtual EventSpace EventSpace { get; set; }
    }
}
