//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodSupplier
    {
        public FoodSupplier()
        {
            this.FoodOrder = new HashSet<FoodOrder>();
        }
    
        public string Name { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string Administrator { get; set; }
    
        public virtual Administrator Administrator1 { get; set; }
        public virtual ICollection<FoodOrder> FoodOrder { get; set; }
    }
}
