//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Message
    {
        [Required(ErrorMessage = "Text Required")]
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string Text { get; set; }
        public System.DateTime Date { get; set; }
        [Required(ErrorMessage = "Text Required")]
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string Topic { get; set; }
        public int Message_ID { get; set; }
        public string Sender { get; set; }
        public string Receiver { get; set; }
        public Message(string id, string logedInUser)
        {
            this.Receiver = id;
            this.Sender = logedInUser;
        }
        public Message()
        {
            this.Date = DateTime.Now;
        }
    
        public virtual Administrator Administrator { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
