//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOrder
    {
        public UserOrder()
        {
            this.Equipment = new HashSet<Equipment>();
            this.FoodOrder = new HashSet<FoodOrder>();
        }
    
        public int Order_code { get; set; }
        public System.DateTime Date { get; set; }
        public double Sum { get; set; }
        public bool is_Paid { get; set; }
        public int Reservation { get; set; }
    
        public virtual ICollection<Equipment> Equipment { get; set; }
        public virtual ICollection<FoodOrder> FoodOrder { get; set; }
        public virtual Reservation Reservation1 { get; set; }
        public virtual EquipmentOrder EquipmentOrder { get; set; }
    }
}
