//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public Worker()
        {
            this.Discount = new HashSet<Discount>();
            this.EventSpace = new HashSet<EventSpace>();
            this.UserReview = new HashSet<UserReview>();
        }
    
        public string email { get; set; }
        public string Username { get; set; }
        public string Boss { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual ICollection<Discount> Discount { get; set; }
        public virtual ICollection<EventSpace> EventSpace { get; set; }
        public virtual RegisteredUser RegisteredUser { get; set; }
        public virtual ICollection<UserReview> UserReview { get; set; }
    }
}
